# Generated by Django 5.0.4 on 2024-06-14 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(null=True, upload_to='media/crispApp/images/')),
                ('pfp_url', models.URLField(blank=True, null=True)),
                ('following', models.ManyToManyField(null=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('instructing', models.ManyToManyField(null=True, related_name='instructing', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
