# Generated by Django 5.0.4 on 2024-06-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0005_remove_userprofile_email_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
