# Generated by Django 5.0.4 on 2024-06-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0006_alter_todo_date_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='title',
        ),
    ]
