# Generated by Django 5.0.4 on 2024-06-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0008_rename_author_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='author',
        ),
    ]
