# Generated by Django 5.0.4 on 2024-06-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0009_rename_user_todo_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
