# Generated by Django 5.0.4 on 2024-07-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0010_delete_userprofile'),
        ('userProfile', '0004_alter_userprofile_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Exclusive', 'Exclusive'), ('Public', 'Public')], default='Private', max_length=9),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.userprofile')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crispApp.todo')),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='submitters',
            field=models.ManyToManyField(through='crispApp.Submission', to='userProfile.userprofile'),
        ),
    ]
