# Generated by Django 5.0.4 on 2024-07-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0011_todo_visibility_submission_todo_submitters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private - Only you can view'), ('Exclusive', 'Exclusive - Shared with your followers'), ('Public', 'Public - Anyone can view')], default='Private', max_length=9),
        ),
    ]
