# Generated by Django 5.0.4 on 2024-07-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0012_alter_todo_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
