# Generated by Django 5.0.4 on 2024-07-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0013_alter_submission_date_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_completed',
        ),
    ]
