# Generated by Django 5.0.4 on 2024-07-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0014_remove_todo_date_completed'),
        ('userProfile', '0004_alter_userprofile_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='userProfile.userprofile'),
        ),
    ]
