# Generated by Django 5.0.4 on 2024-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0016_alter_todo_visibility'),
        ('userProfile', '0005_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='send_to',
            field=models.ManyToManyField(related_name='send_to', to='userProfile.userprofile'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Personal - Only visible to you'), ('Exclusive', 'Exclusive - Send to selective followeres'), ('Public', 'Public - Sent to your followers')], default='Private', max_length=9),
        ),
    ]
