# Generated by Django 5.0.4 on 2024-08-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0017_todo_send_to_alter_todo_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Personal - Only visible to you'), ('Exclusive', 'Exclusive - Send to selective followers'), ('Public', 'Public - Sent to your followers')], default='Private', max_length=9),
        ),
    ]
