# Generated by Django 5.0.4 on 2024-08-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0018_alter_todo_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complete_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Personal - Only visible to you'), ('Exclusive', 'Exclusive - Send to selective followers'), ('Public', 'Public - Send to your followers')], default='Private', max_length=9),
        ),
    ]
