# Generated by Django 5.0.4 on 2024-08-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0019_todo_complete_by_alter_todo_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
