# Generated by Django 5.0.4 on 2024-08-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0021_todo_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Pin',
            new_name='pin',
        ),
    ]
