# Generated by Django 5.0.4 on 2024-08-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0022_rename_pin_todo_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='pin',
        ),
    ]
