# Generated by Django 5.0.4 on 2024-08-13 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0023_remove_todo_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete_by',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
