# Generated by Django 5.0.4 on 2024-08-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0025_remove_todo_complete_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complete_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
