# Generated by Django 5.0.4 on 2024-08-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispApp', '0026_todo_complete_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='complete_by',
        ),
    ]
