# Generated by Django 5.0.4 on 2024-07-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='userProfile.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instructing',
            field=models.ManyToManyField(related_name='instructing', to='userProfile.userprofile'),
        ),
    ]
