# Generated by Django 5.0.4 on 2024-07-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_alter_userprofile_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='followerprofiles', to='userProfile.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instructing',
            field=models.ManyToManyField(related_name='instructingprofiles', to='userProfile.userprofile'),
        ),
    ]
