# Generated by Django 5.0.4 on 2024-07-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_alter_userprofile_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
